version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
    volumes:
      - frontend_build:/app/build
    networks:
      - app-network
  
  backend:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=mysql-container
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=ROOM_BOOKING_SYSTEM
    ports: 
      - "4000:4000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - backend_data:/app/data
    networks:
      - app-network

  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql-container 
    environment:
      - MYSQL_DATABASE=ROOM_BOOKING_SYSTEM
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  frontend_build:
  backend_data:

networks:
  app-network: