version: '3'

services:
  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
    volumes:
      - /app/node_modules
    networks:
      - backend_network
  
  backend:
    build:
      context: ./backend
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_DATABASE}
    env_file:
      - ./backend/.env
    ports: 
      - "4000:4000"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge